### ISSUE TITLE
FFM is officially released in Java 22, any plans to upgrade the dependencies version?

### ISSUE THREAD

**Issue by chengenzhao** [brcolow/java-vulkan#1]
Hi:

FFM is officially released in Java 22, any plans to upgrade the dependencies version?

Thanks

**Comment by chuigda** [comment]
> Hi:
> 
> FFM is officially released in Java 22, any plans to upgrade the dependencies version?
> 
> Thanks

I don't know whether this is the right place, but you may take a look at [vulkan4j](https://vulkan4j.7dg.tech/) ([github](https://github.com/chuigda/vulkan4j)).

**Comment by chengenzhao** [comment]
> > Hi:
> > FFM is officially released in Java 22, any plans to upgrade the dependencies version?
> > Thanks
> 
> I don't know whether this is the right place, but you may take a look at [vulkan4j](https://vulkan4j.7dg.tech/) ([github](https://github.com/chuigda/vulkan4j)).

doesnt really matter now
I made my demo project here: 
https://github.com/chengenzhao/java-vulkan-mac

**Comment by brcolow** [comment]
This was just an experimental project at the time - now others have made full fledged libraries :)
